/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MoveCursorOnStartup
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var MoveCursorOnStartup = class extends import_obsidian.Plugin {
  async onload() {
    let firstNoteOpened = false;
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (!firstNoteOpened && file && file.extension === "md") {
          const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
          if (activeView) {
            setTimeout(() => {
              activeView.editor.exec("goRight");
              activeView.editor.exec("goLeft");
            }, 50);
            firstNoteOpened = true;
          }
        }
      })
    );
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsibWFpbi50cyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiaW1wb3J0IHsgTWFya2Rvd25WaWV3LCBQbHVnaW4sIH0gZnJvbSAnb2JzaWRpYW4nO1xuXG5leHBvcnQgZGVmYXVsdCBjbGFzcyBNb3ZlQ3Vyc29yT25TdGFydHVwIGV4dGVuZHMgUGx1Z2luIHtcblxuXHRhc3luYyBvbmxvYWQoKSB7XG5cblx0XHRsZXQgZmlyc3ROb3RlT3BlbmVkID0gZmFsc2U7XG5cblx0XHR0aGlzLnJlZ2lzdGVyRXZlbnQoXG5cdFx0XHR0aGlzLmFwcC53b3Jrc3BhY2Uub24oJ2ZpbGUtb3BlbicsIChmaWxlKSA9PiB7XG5cdFx0XHRcdGlmICghZmlyc3ROb3RlT3BlbmVkICYmIGZpbGUgJiYgZmlsZS5leHRlbnNpb24gPT09ICdtZCcpIHtcblx0XHRcdFx0XHRjb25zdCBhY3RpdmVWaWV3ID0gdGhpcy5hcHAud29ya3NwYWNlLmdldEFjdGl2ZVZpZXdPZlR5cGUoTWFya2Rvd25WaWV3KTtcblx0XHRcdFx0XHRpZiAoYWN0aXZlVmlldykge1xuXHRcdFx0XHRcdFx0c2V0VGltZW91dCgoKSA9PiB7IC8vIHNsaWdodCBkZWxheVxuXHRcdFx0XHRcdFx0XHRhY3RpdmVWaWV3LmVkaXRvci5leGVjKCdnb1JpZ2h0Jyk7XG5cdFx0XHRcdFx0XHRcdGFjdGl2ZVZpZXcuZWRpdG9yLmV4ZWMoJ2dvTGVmdCcpO1xuXHRcdFx0XHRcdFx0fSwgNTApO1xuXHRcdFx0XHRcdFx0Zmlyc3ROb3RlT3BlbmVkID0gdHJ1ZTtcblx0XHRcdFx0XHR9XG5cdFx0XHRcdH1cblx0XHRcdH0pXG5cdFx0KTtcblx0fVxufSJdLAogICJtYXBwaW5ncyI6ICI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQSxzQkFBc0M7QUFFdEMsSUFBcUIsc0JBQXJCLGNBQWlELHVCQUFPO0FBQUEsRUFFdkQsTUFBTSxTQUFTO0FBRWQsUUFBSSxrQkFBa0I7QUFFdEIsU0FBSztBQUFBLE1BQ0osS0FBSyxJQUFJLFVBQVUsR0FBRyxhQUFhLENBQUMsU0FBUztBQUM1QyxZQUFJLENBQUMsbUJBQW1CLFFBQVEsS0FBSyxjQUFjLE1BQU07QUFDeEQsZ0JBQU0sYUFBYSxLQUFLLElBQUksVUFBVSxvQkFBb0IsNEJBQVk7QUFDdEUsY0FBSSxZQUFZO0FBQ2YsdUJBQVcsTUFBTTtBQUNoQix5QkFBVyxPQUFPLEtBQUssU0FBUztBQUNoQyx5QkFBVyxPQUFPLEtBQUssUUFBUTtBQUFBLFlBQ2hDLEdBQUcsRUFBRTtBQUNMLDhCQUFrQjtBQUFBLFVBQ25CO0FBQUEsUUFDRDtBQUFBLE1BQ0QsQ0FBQztBQUFBLElBQ0Y7QUFBQSxFQUNEO0FBQ0Q7IiwKICAibmFtZXMiOiBbXQp9Cg==
