version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "pydantic"
        versions: [">=2.12.0"]
      - dependency-name: "opentelemetry-exporter-otlp-proto-grpc"
        versions: [">=1.35.0"]
      - dependency-name: "opentelemetry-proto"
        versions: [">=1.35.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
