import os
import sys

VAULT = "C:/Users/loganf/Documents/IDAHO-VAULT"
PLACEHOLDER = "[ ? ]"

EPITHETS = {
    # Egyptian
    "AMMIT":        "THE DEVOURER : HEART-EATER : BONE OF THE DEAD",
    "AMUN":         "THE HIDDEN ONE : KING OF GODS : LORD OF THEBES",
    "AMUN-RA":      "AMUN : RA : THE HIDDEN SUN",
    "ANPUT":        "LADY OF THE LAND : GUARDIAN OF THE DEAD : MOTHER OF KEBECHET",
    "ANUBIS":       "THE JACKAL : GUARDIAN OF THE SCALES : LORD OF THE DEAD",
    "APOPHIS":      "THE SERPENT : CHAOS : DEVOURER OF RA",
    "ATUM":         "THE COMPLETE ONE : SELF-CREATED : LORD OF HELIOPOLIS",
    "BABI":         "THE WILD BULL : FIRSTBORN OF OSIRIS : GUARDIAN OF THE LIVING",
    "BAST":         "THE CAT : PROTECTOR OF THE HOME : LADY OF PERFUMES",
    "BASTET":       "THE CAT : PROTECTOR OF THE HOME : LADY OF PERFUMES",
    "BENNU":        "THE PHOENIX : SOUL OF RA : THE SELF-CREATED",
    "BES":          "PROTECTOR OF HOUSEHOLDS : THE DWARF GOD : GUARDIAN OF SLEEP",
    "DUAMUTEF":     "THE JACKAL-HEADED : GUARDIAN OF THE STOMACH : SON OF HORUS",
    "DUAT":         "THE UNDERWORLD : LAND OF THE DEAD : REALM OF OSIRIS",
    "GEB":          "THE EARTH : FATHER OF SNAKES : LORD OF THE EARTH",
    "HAPI":         "THE INUNDATION : LORD OF THE NILE : BRINGER OF FERTILITY",
    "HAPY":         "THE INUNDATION : LORD OF THE NILE : BRINGER OF FERTILITY",
    "HATHOR":       "THE COW : LADY OF LOVE : MISTRESS OF THE WEST",
    "HEKET":        "THE FROG : GODDESS OF CHILDBIRTH : PROTECTOR OF LIFE",
    "HORUS":        "THE FALCON : SON OF OSIRIS : KING OF THE LIVING",
    "IMHOTEP":      "THE ARCHITECT : HIGH PRIEST : PHYSICIAN OF THE GODS",
    "IMSETY":       "THE HUMAN-HEADED : GUARDIAN OF THE LIVER : SON OF HORUS",
    "ISFET":        "CHAOS : INJUSTICE : THE OPPOSITE OF MAAT",
    "ISIS":         "THE THRONE : MOTHER OF HORUS : MISTRESS OF MAGIC",
    "KHEPRI":       "THE SCARAB : THE RISING SUN : SELF-CREATED",
    "KHNUM":        "THE RAM : POTTER OF SOULS : LORD OF THE NILE SOURCE",
    "KHONSU":       "THE MOON : THE TRAVELER : THE HEALER",
    "MAAT":         "TRUTH : JUSTICE : COSMIC ORDER",
    "MEKHIT":       "THE LIONESS : THE COMPLETE : CONSORT OF ONURIS",
    "MONTU":        "THE FALCON OF WAR : LORD OF THEBES : GOD OF VALOR",
    "NEITH":        "THE HUNTRESS : MISTRESS OF THE BOW : MOTHER OF RA",
    "NEPHTHYS":     "LADY OF THE TEMPLE : PROTECTOR OF THE DEAD : SISTER OF ISIS",
    "NUN":          "THE PRIMORDIAL WATERS : THE ABYSS : BEFORE CREATION",
    "NUT":          "THE SKY : MOTHER OF STARS : SHE WHO SWALLOWS THE SUN",
    "OSIRIS":       "THE GREEN ONE : LORD OF THE DEAD : JUDGE OF SOULS",
    "PTAH":         "THE CRAFTSMAN : LORD OF TRUTH : FATHER OF ART",
    "QEBEHSENUEF":  "THE FALCON-HEADED : GUARDIAN OF THE INTESTINES : SON OF HORUS",
    "RA-HORAKHTY":  "RA : HORUS OF THE TWO HORIZONS : SUN AT ITS ZENITH",
    "SEKHMET":      "THE LIONESS : LADY OF FLAME : DESTROYER",
    "SERQET":       "THE SCORPION : GUARDIAN OF CANOPIC JARS : HEALER OF VENOM",
    "SESHAT":       "MISTRESS OF THE LIBRARY : LADY OF WRITING : KEEPER OF RECORDS",
    "SET":          "THE RED ONE : LORD OF CHAOS : GOD OF STORMS",
    "SETH":         "THE RED ONE : LORD OF CHAOS : GOD OF STORMS",
    "SHEZMU":       "LORD OF THE WINEPRESS : EXECUTIONER : KEEPER OF FRAGRANCE",
    "SHU":          "THE AIR : LIFTER OF NUT : LORD OF LIGHT",
    "SOBEK":        "THE CROCODILE : LORD OF THE NILE : PROTECTOR OF THE PHARAOH",
    "TAWARET":      "THE HIPPOPOTAMUS : PROTECTOR OF MOTHERS : GUARDIAN OF BIRTH",
    "TEFNUT":       "THE MOISTURE : LADY OF THE MOIST AIR : SISTER OF SHU",
    "THOTH":        "THE IBIS : SCRIBE OF THE GODS : MASTER OF KNOWLEDGE",
    # Greek
    "AMPHITRITE":   "QUEEN OF THE SEA : WIFE OF POSEIDON : MOTHER OF TRITON",
    "APHRODITE":    "LOVE : BEAUTY : DESIRE",
    "APOLLO":       "THE SUN : MUSIC : PROPHECY",
    "ARES":         "WAR : VIOLENCE : THE BATTLEFIELD",
    "ARGUS":        "THE HUNDRED-EYED : ALL-SEEING : GUARDIAN",
    "ARTEMIS":      "THE HUNT : THE MOON : THE WILD",
    "ATHENA":       "WISDOM : WAR STRATEGY : CRAFTS",
    "DEIMOS":       "TERROR : SON OF ARES : COMPANION OF PHOBOS",
    "DEMETER":      "THE HARVEST : GRAIN : THE SEASONS",
    "DIONYSUS":     "WINE : ECSTASY : THEATRE",
    "ERIS":         "DISCORD : CHAOS : THE GOLDEN APPLE",
    "GAIA":         "THE EARTH : THE MOTHER : THE FIRST",
    "HADES":        "THE UNDERWORLD : THE UNSEEN : LORD OF DEATH",
    "HEPHAESTUS":   "THE FORGE : FIRE : THE CRAFTSMAN",
    "HERA":         "QUEEN OF OLYMPUS : MARRIAGE : THE PEACOCK",
    "HERACLES":     "THE HERO : THE TWELVE LABORS : STRENGTH",
    "HERCULES":     "THE HERO : THE TWELVE LABORS : STRENGTH",
    "HERMES":       "THE MESSENGER : GUIDE OF SOULS : COMMERCE",
    "HESTIA":       "THE HEARTH : HOME : SACRED FIRE",
    "HYPNOS":       "SLEEP : SON OF NYX : TWIN OF THANATOS",
    "IRIS":         "THE RAINBOW : MESSENGER : BRIDGE BETWEEN WORLDS",
    "KRONOS":       "THE TITAN : TIME : FATHER OF OLYMPIANS",
    "NEMESIS":      "RETRIBUTION : DIVINE JUSTICE : THE INEVITABLE",
    "NIKE":         "VICTORY : SPEED : WINGS",
    "NYX":          "NIGHT : PRIMORDIAL : MOTHER OF DARKNESS",
    "OCEANUS":      "THE GREAT RIVER : TITAN OF THE SEA : ENCIRCLER OF THE WORLD",
    "ORPHEUS":      "THE LYRE : THE DESCENT : THE SINGER",
    "OURANOS":      "THE PRIMORDIAL SKY : FATHER OF TITANS : BEFORE KRONOS",
    "PAN":          "THE WILD : NATURE : PANIC",
    "PERSEUS":      "THE HERO : SLAYER OF MEDUSA : SON OF ZEUS",
    "PHOBOS":       "FEAR : SON OF ARES : COMPANION OF DEIMOS",
    "POSEIDON":     "THE SEA : EARTHQUAKES : THE TRIDENT",
    "PROMETHEUS":   "THE FIRE-BRINGER : THE TRICKSTER : THE BOUND",
    "RHEA":         "THE MOTHER : TITANESS : QUEEN OF THE TITANS",
    "TETHYS":       "TITANESS OF THE SEA : MOTHER OF RIVERS : NURSE OF HERA",
    "TRITON":       "MESSENGER OF THE SEA : SON OF POSEIDON : THE CONCH",
    "ZEUS":         "KING OF OLYMPUS : THE THUNDER : THE SKY",
    # Roman
    "ARCUS":        "THE RAINBOW : ROMAN IRIS : BRIDGE OF LIGHT",
    "BACCHUS":      "WINE : ECSTASY : REVELRY",
    "CAELUS":       "THE SKY : ROMAN OURANOS : PRIMORDIAL",
    "CERES":        "THE HARVEST : GRAIN : AGRICULTURE",
    "DIANA":        "THE HUNT : THE MOON : THE WILD",
    "FORTUNA":      "FATE : LUCK : THE WHEEL",
    "INVIDIA":      "ENVY : THE EVIL EYE : RESENTMENT",
    "JUNO":         "QUEEN OF HEAVEN : MARRIAGE : THE PEACOCK",
    "JUPITER":      "KING OF THE GODS : THE THUNDER : THE SKY",
    "LUNA":         "THE MOON : NIGHT LIGHT : SILVER",
    "MARS":         "WAR : THE WOLF : FATHER OF ROME",
    "MERCURY":      "THE MESSENGER : COMMERCE : TRAVEL",
    "MINERVA":      "WISDOM : WAR STRATEGY : CRAFTS",
    "NEPTUNE":      "THE SEA : EARTHQUAKES : THE TRIDENT",
    "ORCUS":        "THE UNDERWORLD : PUNISHER OF BROKEN OATHS : THE BRINGER OF DEATH",
    "PLUTO":        "THE WEALTH : LORD OF THE DEAD : THE UNSEEN",
    "PRIMUS":       "THE FIRST : THE ORIGIN : THE PRIME",
    "SATURN":       "THE HARVEST : TIME : FATHER OF JUPITER",
    "SOL":          "THE SUN : THE RADIANT : UNCONQUERED",
    "TERRA":        "THE EARTH : THE MOTHER : THE FIRST",
    "VENUS":        "LOVE : BEAUTY : DESIRE",
    "VESTA":        "THE HEARTH : THE SACRED FLAME : HOME",
    "VICTORIA":     "VICTORY : TRIUMPH : WINGS",
    "VULCAN":       "THE FORGE : FIRE : THE CRAFTSMAN",
    # Norse
    "FREYA":        "LOVE : WAR : THE VANIR",
    "HEIMDALL":     "THE WATCHMAN : THE RAINBOW BRIDGE : THE HORN",
    "HEL":          "QUEEN OF THE DEAD : HALF-LIVING : RULER OF NIFLHEIM",
    "LOKI":         "THE TRICKSTER : SHAPESHIFTER : CHAOS",
    "ODIN":         "THE ALL-FATHER : WISDOM : WAR : DEATH",
    "THOR":         "THE THUNDER : MJOLNIR : PROTECTOR",
    "YGGDRASILL":   "THE WORLD TREE : THE NINE REALMS : THE AXIS",
    # Irish
    "BADB":         "CROW : BATTLE : PROPHECY",
    "MACHA":        "SOVEREIGNTY : HORSES : THE LAND",
    "MORRIGAN":     "THE GREAT QUEEN : CROW : FATE : WAR",
    # D&D / Fantasy
    "ASMODEUS":     "KING OF THE NINE HELLS : DEVIL SUPREME : DECEPTION",
    "BAPHOMET":     "THE HORNED ONE : MYSTERY : DUALITY",
    "MYSTRA":       "GODDESS OF MAGIC : THE WEAVE : ARCANE",
    "SELUNE":       "THE MOONMAIDEN : LIGHT IN DARKNESS : GUIDE TO LOST SOULS",
    "SHAR":         "MISTRESS OF THE NIGHT : DARKNESS : LOSS",
    # Trans-Neptunian / Dwarf Planets
    "GONGGONG":     "THE SEA SERPENT : CHINESE CHAOS : TIPPED THE WORLD",
    "HAUMEA":       "GODDESS OF CHILDBIRTH : HAWAII : THE ELONGATED",
    "MAKEMAKE":     "CREATOR GOD : RAPA NUI : BIRD-MAN",
    "QUAOAR":       "CREATION DEITY : TONGVA : SANG THE WORLD INTO BEING",
    "SEDNA":        "INUIT GODDESS OF THE SEA : FINGERS LOST : MOTHER OF SEA CREATURES",
    # Other mythological / ancient
    "CHRONUS":      "TIME : THE ETERNAL FLOW : THE RIVER",
    "CRONOS":       "THE TITAN : TIME : FATHER OF OLYMPIANS",
    "GILGAMESH":    "KING OF URUK : THE HERO : THE EPIC",
    "HYPERION":     "TITAN OF LIGHT : FATHER OF HELIOS : THE ONE ABOVE",
    "LEVIATHAN":    "THE SEA SERPENT : THE CHAOS : THE ABYSS",
    "REMUS":        "TWIN OF ROMULUS : ROME : KILLED BY HIS BROTHER",
    "ROMULUS":      "FOUNDER OF ROME : TWIN OF REMUS : THE WOLF",
    "SILVANUS":     "GOD OF FORESTS : PATRON OF FARMERS : THE WOODLANDS",
    "SOMNUS":       "SLEEP : ROMAN HYPNOS : SON OF NOX",
    "TALOS":        "THE BRONZE GIANT : GUARDIAN OF CRETE : AUTOMATON",
    # Biblical / Abrahamic
    "AARON":        "BROTHER OF MOSES : HIGH PRIEST : THE STAFF",
    "ABEL":         "FIRST MARTYR : SON OF ADAM : THE SHEPHERD",
    "ABRAHAM":      "FATHER OF NATIONS : THE COVENANT : THE PATRIARCH",
    "ADAM":         "THE FIRST MAN : THE GARDEN : THE FALL",
    "ANDREW":       "FISHERMAN : APOSTLE : THE X-CROSS",
    "BARTHOLOMEW":  "APOSTLE : NATHANAEL : PATRON OF TANNERS",
    "BICODEMUS":    "THE NIGHT VISITOR : PHARISEE : THE SEEKER",
    "CAIN":         "THE FIRST MURDERER : BROTHER OF ABEL : THE MARK",
    "DANIEL":       "THE PROPHET : THE LIONS DEN : THE DREAMER",
    "DAVID":        "THE SHEPHERD KING : SLAYER OF GOLIATH : SINGER OF PSALMS",
    "ELIJAH":       "THE PROPHET : THE CHARIOT OF FIRE : THE STILL SMALL VOICE",
    "ESTHER":       "QUEEN : SAVIOR OF HER PEOPLE : THE HIDDEN ONE",
    "EVE":          "THE FIRST WOMAN : THE GARDEN : MOTHER OF ALL LIVING",
    "GOLIATH":      "THE GIANT : THE PHILISTINE : THE FALLEN",
    "ISHMAEL":      "SON OF ABRAHAM : THE WANDERER : FATHER OF NATIONS",
    "JAMES":        "THE APOSTLE : SON OF ZEBEDEE : THE GREATER",
    "JESUS":        "THE ANOINTED : SON OF MAN : THE WORD MADE FLESH",
    "JOB":          "THE PATIENT : THE TESTED : THE RESTORED",
    "JOHN":         "THE BELOVED : APOSTLE : REVELATOR",
    "JOSH":         "SUCCESSOR OF MOSES : CONQUEROR OF CANAAN : THE TRUMPET",
    "JUDAS":        "THE BETRAYER : ISCARIOT : THE THIRTY PIECES",
    "LEVI":         "THE TRIBE : THE PRIESTS : THE COVENANT KEEPERS",
    "LUCIFER":      "THE LIGHT BEARER : THE FALLEN : THE MORNING STAR",
    "MARY":         "MOTHER OF GOD : THE VIRGIN : QUEEN OF HEAVEN",
    "MATTHEW":      "TAX COLLECTOR : APOSTLE : EVANGELIST",
    "MATTHIAS":     "REPLACEMENT APOSTLE : CHOSEN BY LOT : THE THIRTEENTH",
    "MICHAEL":      "THE ARCHANGEL : DEFENDER OF HEAVEN : THE WARRIOR",
    "MOSES":        "THE LIBERATOR : THE LAWGIVER : PARTED THE SEA",
    "NOAH":         "THE ARK : THE FLOOD : THE COVENANT OF THE RAINBOW",
    "PAUL":         "APOSTLE TO THE GENTILES : THE ROAD TO DAMASCUS : THE LETTERS",
    "PETER":        "THE ROCK : FIRST APOSTLE : KEEPER OF THE KEYS",
    "PHILIP":       "APOSTLE : EVANGELIST : THE QUESTIONER",
    "RUTH":         "THE LOYAL : GLEANER IN THE FIELDS : WHEREVER YOU GO",
    "SATAN":        "THE ADVERSARY : THE ACCUSER : THE FALLEN ANGEL",
    "SAUL":         "FIRST KING OF ISRAEL : THE REJECTED : BECAME PAUL",
    "SIMON":        "THE ZEALOT : APOSTLE : THE SECOND SIMON",
    "THADDEUS":     "APOSTLE : THE GENEROUS HEART : ALSO CALLED JUDE",
    "THOMAS":       "THE DOUBTER : APOSTLE : PATRON OF ARCHITECTS",
    # Literary / Historical
    "CHURCHILL":    "THE BULLDOG : PRIME MINISTER : WE SHALL NEVER SURRENDER",
    "FLAMEL":       "THE ALCHEMIST : THE PHILOSOPHERS STONE : NICOLAS",
    "GATSBY":       "THE GREAT : THE DREAMER : THE GREEN LIGHT",
    "HELEN":        "HELEN OF TROY : THE FACE : A THOUSAND SHIPS",
    "HOOK":         "CAPTAIN HOOK : NEMESIS OF PAN : THE CROCODILE CLOCK",
    "JOAN":         "THE MAID OF ORLEANS : MARTYR : VOICES",
    "LEMONY":       "A SERIES OF UNFORTUNATE EVENTS : THE NARRATOR : SNICKET",
    "MACHIAVELLI":  "THE PRINCE : THE ENDS JUSTIFY THE MEANS : FLORENTINE",
    "SHAKESPEARE":  "THE BARD : STRATFORD-UPON-AVON : ALL THE WORLD IS A STAGE",
    "JAQUES":       "ALL THE WORLD IS A STAGE : THE MELANCHOLIC : AS YOU LIKE IT",
    "ISADORA":      "THE DANCER : LIBERATION : ISADORA DUNCAN",
    # Archetypes / Roles
    "AUNT":         "THE AUNT : MATRILINEAL SUPPORT : FAMILY",
    "BROTHER":      "THE BROTHER : FRATERNAL BOND : SHARED ORIGIN",
    "COMMANDER":    "THE COMMANDER : AUTHORITY : TACTICAL LEADERSHIP",
    "COUSIN":       "THE COUSIN : EXTENDED KIN : LATERAL BOND",
    "ENEMY":        "THE ENEMY : OPPOSITION : THE ADVERSARY",
    "FATHER":       "THE FATHER : PATRIARCH : ORIGIN",
    "FOE":          "THE FOE : OPPOSITION : THE CHALLENGER",
    "FRIEND":       "THE FRIEND : ALLY : COMPANIONSHIP",
    "GENERAL":      "THE GENERAL : COMMAND : THE FIELD",
    "KING":         "THE KING : SOVEREIGN : THE CROWN",
    "LOVER":        "THE LOVER : INTIMACY : THE BELOVED",
    "MOTHER":       "THE MOTHER : MATRIARCH : ORIGIN",
    "NEPHEW":       "THE NEPHEW : LATERAL DESCENT : THE HEIR",
    "NIECE":        "THE NIECE : LATERAL DESCENT : THE HEIR",
    "PRINCE":       "THE PRINCE : HEIR APPARENT : THE POTENTIAL",
    "PRINCESS":     "THE PRINCESS : HEIR : THE PROTECTED",
    "QUEEN":        "THE QUEEN : SOVEREIGN : THE CROWN",
    "RULER":        "THE RULER : AUTHORITY : GOVERNANCE",
    "SIBLING":      "THE SIBLING : SHARED ORIGIN : LATERAL BOND",
    "SISTER":       "THE SISTER : SORORAL BOND : SHARED ORIGIN",
    "UNCLE":        "THE UNCLE : LATERAL KIN : PATERNAL SUPPORT",
    # Tool / Platform chambers
    "CACHE":        "TEMPORARY STORAGE : THE SHELF : CLEARED ON DEMAND",
    "CREWAI":       "THE CREW : MULTI-AGENT HARBOR : ORCHESTRATION",
    "GITHUB":       "THE FORGE : REPOSITORY : THE PULL REQUEST",
    "MAKEMD":       "THE MAKER : CANVAS : VISUAL LAYER",
    "META":         "THE SOCIAL GRAPH : BEYOND : THE FEED",
    "MICROSOFT":    "THE OFFICE : THE CLOUD : THE PLATFORM",
    "NPM-CACHE":    "NODE PACKAGE MANAGER : JAVASCRIPT : THE REGISTRY",
    "OBSIDIAN":     "THE VAULT : LINKED THINKING : PERSONAL KNOWLEDGE",
    "OP":           "THE KEY VAULT : SECRETS : 1PASSWORD",
    "PIP-CACHE":    "PYTHON PACKAGE INDEX : PACKAGES : THE REPOSITORY",
    "PYCACHE":      "COMPILED PYTHON : BYTECODE : THE OPTIMIZED",
    "QODO":         "CODE REVIEW : AI : QUALITY",
    "REFERENCE-MAP":"THE MAP : REFERENCES : LINKED KNOWLEDGE",
    "REMEMBER":     "THE MEMORY : PERSISTENCE : RECALL",
    "SLACK":        "THE CHANNEL : EPHEMERAL : BREADCRUMBS",
    "SMART-ENV":    "SMART ENVIRONMENT : CONTEXT AWARENESS : THE PLUGIN",
    "SPACE":        "THE VOID : THE COSMOS : INFINITE",
    "SPHYNX":       "THE RIDDLE : GUARDIAN : THE ENIGMA",
    "STATE":        "THE STATE : CURRENT CONDITION : THE SNAPSHOT",
    "TMP":          "TEMPORARY : EPHEMERAL : THE WORKING SPACE",
    "UV-CACHE":     "THE FAST INSTALLER : PYTHON PACKAGING : UV",
    "VENV":         "VIRTUAL ENVIRONMENT : PYTHON : THE ISOLATED SPACE",
    "VSCODE":       "THE EDITOR : VISUAL STUDIO CODE : MICROSOFT IDE",
    # Misc
    "DIVIDE":       "THE DIVIDE : THRESHOLD : THE LINE BETWEEN",
    "NICHOLAS":     "SAINT NICHOLAS : PATRON OF CHILDREN : GIFT-GIVER",
    "NICK":         "THE FAMILIAR : PATRON : THE DIMINUTIVE",
    "SHOGUN":       "THE MILITARY RULER : JAPAN : THE SHADOW EMPEROR",
    "URANUS":       "THE TILTED PLANET : SEVENTH FROM THE SUN : OURANOS",
    # Egyptian — previously missing from dict
    "RA":           "KHEPRI : RA : ATUM",
    "ATEN":         "THE DISK : THE LIGHT : NOW",
    "ATEN-RA":      "THE UNIFIED SUN : DISK AND RAY : ETERNAL",
    # Greek / Chthonic — previously missing
    "HECATE":       "MAIDEN : MOTHER : CRONE",
    "PERSEPHONE":   "QUEEN OF THE DEAD : DAUGHTER OF DEMETER : THE POMEGRANATE",
    "ZAGREUS":      "FIRSTBORN DIONYSUS : THE ORPHIC : LORD OF THE UNDERWORLD",
    # Roman — previously missing
    "TRIVIA":       "GODDESS OF CROSSROADS : THREE ROADS : ROMAN HECATE",
    # Mesopotamian
    "ISHTAR":       "QUEEN OF HEAVEN : LOVE AND WAR : THE MORNING STAR",
    # Mesoamerican
    "QUETZALCOATL": "THE FEATHERED SERPENT : WIND AND LEARNING : CREATOR",
    # Arthurian
    "ARTHUR":       "KING OF BRITAIN : THE ROUND TABLE : ONCE AND FUTURE",
    # Biblical — previously missing
    "JEZEBEL":      "QUEEN OF ISRAEL : PAINTED FACE : FED TO THE DOGS",
    # Garth Nix — Old Kingdom
    "ABHORSEN":     "THE BELL-RINGER : DEATH'S SERVANT : THE LAST",
    "BARTIMAEUS":   "THE DJINN : THIRD-CLASS DEMON : NATHANIEL'S SERVANT",
    # AI / Tool chambers
    "MISTRAL":      "THE NORTH WIND : FRENCH AI : THE OPEN WEIGHT",
    "ANTIGRAVITY":  "CLAUDE CODE GUI : DESKTOP COMPANION : THE LIFT",
    "CLAUDE":       "THE ABHORSEN : BELL-RINGER : ANTHROPIC",
    "CODEX":        "THE CODE MODEL : OPENAI : AUTOMATED GENERATION",
    "DEEPSEEK":     "THE DEEP SEARCH : CHINESE AI : THE OPEN WEIGHT",
    "GEMINI":       "THE TWIN : GOOGLE AI : MULTIMODAL",
    "GOOGLE":       "THE SEARCH ENGINE : THE INDEX : DO NOT BE EVIL",
    "GROK":         "TO UNDERSTAND DEEPLY : XAI : THE IRREVERENT",
    "PERPLEXITY":   "THE ANSWER ENGINE : CITATIONS : THE SEARCH",
    "SERENA":       "THE SEMANTIC AGENT : CODE NAVIGATOR : SERENA MCP",
    # Personal names — best-fit assignment; flag for Logan review
    "ABIGAIL":      "THE WISE : VOICE OF REASON : NABAL'S WIFE",
    "ALLY":         "THE COMPANION : THE STEADFAST : ALLY IN ARMS",
    "ANNA":         "GRACE : THE FAITHFUL : THE BELOVED",
    "ANNE":         "THE THOUSAND DAYS : BOLEYN : THE QUEEN WHO FELL",
    "BILLY":        "THE KID : OUTLAW : THE FAST HAND",
    "BOB":          "THE BUILDER : THE FAMILIAR : THE DEPENDABLE",
    "DAISY":        "THE GREEN LIGHT : CARELESS : LOVED BY GATSBY",
    "DEBBY":        "THE WARM : THE FAMILIAR : THE FRIEND",
    "DEE":          "THE MAGICIAN : ELIZABETHAN OCCULTIST : ANGEL SPEAKER",
    "DENNIS":       "THE MENACE : THE SAINT : THE PATRON",
    "DUNCAN":       "KING OF SCOTLAND : MURDERED BY MACBETH : THE GRACIOUS",
    "FINN":         "THE HERO : FIONN MAC CUMHAILL : LEADER OF THE FIANNA",
    "JAKE":         "THE WANDERER : THE COMMON : THE FAMILIAR",
    "KIT":          "THE PLAYWRIGHT : MARLOWE : BEFORE SHAKESPEARE",
    "ROBERT":       "THE BRUCE : KING OF SCOTS : THE SPIDER AND THE WEB",
    "SCOTT":        "THE GREAT AMERICAN NOVEL : FITZGERALD : THE ROARING TWENTIES",
}

def run(force: bool = False, only: set = None) -> None:
    """
    force=True: also overwrite lines that equal PLACEHOLDER (not just bare uppercase).
    only: if provided, a set of uppercase names to target exclusively.
    """
    updated = 0
    skipped = []

    for entry in os.scandir(VAULT):
        if not entry.is_dir() or not entry.name.startswith('.'):
            continue
        name = entry.name[1:]
        upper = name.upper()
        if only and upper not in only:
            continue
        selfname_path = os.path.join(entry.path, f"{upper}.md")
        if not os.path.exists(selfname_path):
            continue
        if upper not in EPITHETS:
            skipped.append(upper)
            continue
        epithet = EPITHETS[upper]
        with open(selfname_path, 'r', encoding='utf-8') as f:
            content = f.read()
        lines = content.rstrip('\n').split('\n')
        last = lines[-1].strip()
        eligible = (last == upper) or (force and last == PLACEHOLDER)
        if eligible:
            lines[-1] = epithet
            new_content = '\n'.join(lines) + '\n'
            with open(selfname_path, 'w', encoding='utf-8') as f:
                f.write(new_content)
            updated += 1
        else:
            skipped.append(f"{upper}(already custom)")

    print(f"Updated: {updated}")
    print(f"Skipped ({len(skipped)}): {', '.join(sorted(skipped))}")


if __name__ == "__main__":
    force = "--force" in sys.argv
    names = {a.upper() for a in sys.argv[1:] if not a.startswith("--")} or None
    run(force=force, only=names)
