model = "gpt-5.5"
model_reasoning_effort = "high"
approvals_reviewer = "auto_review"
personality = "friendly"
[projects."/Users/logan"]
trust_level = "trusted"

[projects."/Users/logan/IDAHO-VAULT"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4

[plugins."linear@openai-curated"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."canva@openai-curated"]
enabled = true

[plugins."figma@openai-curated"]
enabled = true

[plugins."hugging-face@openai-curated"]
enabled = true

[plugins."box@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."atlassian-rovo@openai-curated"]
enabled = true

[plugins."vercel@openai-curated"]
enabled = true

[plugins."twilio-developer-kit@openai-curated"]
enabled = true

[plugins."test-android-apps@openai-curated"]
enabled = true

[plugins."supabase@openai-curated"]
enabled = true

[plugins."superpowers@openai-curated"]
enabled = true

[plugins."temporal@openai-curated"]
enabled = true

[plugins."stripe@openai-curated"]
enabled = true

[plugins."sentry@openai-curated"]
enabled = true

[plugins."build-ios-apps@openai-curated"]
enabled = true

[plugins."build-macos-apps@openai-curated"]
enabled = true

[plugins."build-web-apps@openai-curated"]
enabled = true

[plugins."otter-ai@openai-curated"]
enabled = true

[plugins."openai-developers@openai-curated"]
enabled = true

[plugins."clickup@openai-curated"]
enabled = true

[profiles.ollama-launch]
openai_base_url = "http://127.0.0.1:11434/v1/"
forced_login_method = "api"
model_provider = "ollama-launch"

[model_providers.ollama-launch]
name = "Ollama"
base_url = "http://127.0.0.1:11434/v1/"

[features]
memories = true
prevent_idle_sleep = true

[mcp_servers.obsidian-vault]
url = "http://localhost:27124"
bearer_token_env_var = "OBSIDIAN_LOCAL_REST_API_KEY"
