[project]
name = "idaho-vault"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "flask>=3.1.0",
  "pygit2>=1.18.2",
  "pyyaml>=6.0.3",
  "posthog>=7.38.4,<8",
]

[dependency-groups]
dev = [
  "pytest>=9.1.1",
  "pytest-codspeed>=5.0.3",
]


[project.urls]
Repository = "https://github.com/LAF-US/IDAHO-VAULT"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
