[[rule]]
decision = "allow"
priority = 950
toolName = "save_memory"
modes = [ "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "replace"
argsPattern = '\\0\"file_path\":\"c:/users/loganf/documents/idaho\-vault/!/agents\.md\"\\0'
modes = [ "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "replace"
argsPattern = '\\0\"file_path\":\"c:/users/loganf/documents/idaho\-vault/levelset\-current\.md\"\\0'
modes = [ "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "replace"
argsPattern = '\\0\"file_path\":\"c:/users/loganf/documents/idaho\-vault/!/GRIMOIRE/TRIUNE\-TRIPTYCH\-TRIUMVIRATE\.md\"\\0'
modes = [ "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "replace"
argsPattern = '\\0\"file_path\":\"c:/users/loganf/documents/idaho\-vault/!VAULTED\-CENSUS\-2026\-04\-12\.md\"\\0'
modes = [ "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "gcloud" ]
modes = [ "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "gh" ]
modes = [ "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "replace"
argsPattern = '\\0\"file_path\":\"\.github/workflows/auto\-pr\.yml\"\\0'
modes = [ "default", "autoEdit", "yolo" ]
