#!/usr/bin/env python3
"""
Linker Crew — Phase 2: Entity Mapping (The Linker)
Part of the [STABILIZE }!{ IGNITE] v2 plan.

ADJUSTMENT: [Omega to Alpha] — Files are scanned in REVERSE order.

This script scans the factual notes discovered in Phase 1 and 
identifies mentions of other vault stubs (23k+ total). 
It produces a proposal for 'related' metadata links.

LINUX }!{ — targets Linux-native execution.
"""

import os
import re
import json
from datetime import datetime, timezone
from pathlib import Path

# --- Configuration ---
VAULT_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT_JSON = VAULT_ROOT / "!" / "CREWAI" / "LINKER-PROPOSAL-v1.json"
OUTPUT_MD = VAULT_ROOT / "!" / "CREWAI" / "LINKER-SUMMARY-v1.md"
EXCLUSIONS = ["!", "swarm", ".github", ".obsidian", "INBOX", "node_modules", "vendor"]

def get_all_stubs():
    """Retrieves all .md stub filenames (sans extension) in the root."""
    stubs = set()
    for item in VAULT_ROOT.iterdir():
        if item.is_file() and item.suffix == ".md":
            stubs.add(item.stem) # The filename without .md
    return stubs

def run_linker():
    """Iterates through factual notes and matches against stubs."""
    stubs = get_all_stubs()
    proposal = {}
    stats = {
        "notes_scanned": 0,
        "notes_with_links": 0,
        "total_links_found": 0,
    }

    print(f"Igniting The Linker [Omega -> Alpha]... Loaded {len(stubs)} stubs.")

    # LIST AND SORT FILES REVERSE (Omega to Alpha)
    items = sorted([f for f in VAULT_ROOT.iterdir()], key=lambda x: x.name, reverse=True)

    # iterate through all root files
    for item in items:
        # Only process .md files not in exclusions
        if item.is_file() and item.suffix == ".md" and not any(ex in item.parts for ex in EXCLUSIONS):
            try:
                content = item.read_text(encoding="utf-8")
                if len(content.strip()) > 0:
                    stats["notes_scanned"] += 1
                    matches = []
                    
                    # Optimization: only check stubs that are at least 3 chars long to avoid noise
                    for stub in stubs:
                        if len(stub) < 3: continue
                        if stub == item.stem: continue # Don't link to self
                        
                        # Quick check before regex
                        if stub in content:
                            # Use regex to ensure word boundaries
                            pattern = r"\b" + re.escape(stub) + r"\b"
                            if re.search(pattern, content):
                                matches.append(stub)
                    
                    if matches:
                        proposal[item.name] = sorted(list(set(matches)))
                        stats["notes_with_links"] += 1
                        stats["total_links_found"] += len(matches)
                
                if stats["notes_scanned"] % 500 == 0:
                    print(f"Scanned {stats['notes_scanned']} notes...")

            except Exception as e:
                print(f"Error processing {item.name}: {e}")

    return proposal, stats

def write_results(proposal, stats):
    """Writes JSON and Markdown summaries."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    # Ensure directory exists
    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)

    # Write JSON
    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump({
            "metadata": {
                "timestamp": now,
                "stats": stats,
                "logic": "Case-sensitive regex [REVERSE SCAN: Omega -> Alpha]"
            },
            "proposal": proposal
        }, f, indent=4)

    # Write Markdown Summary
    md_content = f"""---
title: "LINKER-SUMMARY-v1 — Phase 2 Proposal"
updated: "{now[:10]}"
status: draft
authority: "LOGAN"
doc_class: index
---

# Phase 2 Linker Proposal — {now[:10]}

The Linker has completed the **Omega to Alpha (Reverse)** pass instructed by The Architect.

## Execution Stats
- **Notes Scanned**: {stats["notes_scanned"]}
- **Notes with Proposed Links**: {stats["notes_with_links"]}
- **Total Links Identified**: {stats["total_links_found"]}
- **Avg Links/Note**: {stats["total_links_found"] / stats["notes_with_links"] if stats["notes_with_links"] > 0 else 0:.2f}

## Sample Matches (Omega/Top of Scan)
| Source File | Proposed Related Links |
|-------------|------------------------|
"""
    # Show first 10 samples (which are the beginning of the reverse scan)
    samples = list(proposal.items())[:10]
    for filename, links in samples:
        links_str = ", ".join(links[:5]) + ("..." if len(links) > 5 else "")
        md_content += f"| {filename} | {links_str} |\n"

    md_content += f"""
---
*Generated by Bartimaeus (Gemini) — UNIFICATION STREAM Phase 2 (Adjusted per Architect)*
"""
    OUTPUT_MD.write_text(md_content, encoding="utf-8")
    return f"Proposal written to {OUTPUT_JSON.name} and {OUTPUT_MD.name}"

if __name__ == "__main__":
    proposal, stats = run_linker()
    msg = write_results(proposal, stats)
    print(f"Linker complete. {msg}")
